export const environment = {
  production: true,
  APP_TITLE: "ระบบขอใช้เปลออนไลน์",
  API_URL: "http://localhost:4200/",
  node_api_url: "https://api.reh.go.th/comservice",
  // node_api_url: 'http://localhost:8082',
  node_api_his: "https://api.reh.go.th/rehapi-backend-his",
  node_static_url: "https://api.reh.go.th/comservice/public",
  baseUrl: "/app-rider",
  token: "token_32",
  version: "1.4.7",
  appId: "32",
  managerRole: 6,
  adminRole: 5,
  userRole: 0,
  LOGIN_STATUS:'STATUS',
  ACCESS_TOKENS:'accessToken',
  REFRESH_TOKENS:'refreshToken',
  accessKeySecret:"96Udcddbo9y[gfHdovos]y["
};
